# Generated by Django 5.0.7 on 2024-08-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_rename_dob_employee_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Date_Of_Birth',
            field=models.DateField(max_length=100),
        ),
    ]
